name: Basic Checkout Lab

on:
  push:
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG = true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Curent Directory: $(pwd)"

      - name: Check versions
        run: |
          echo "Node version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Git version: $(git --version)"

      - name: Some new commands
        run: |
          echo "Current date and time: $(date)"
          echo "Available disk space: $(df -h)"
          echo "Memory usage: $(-m)"

      - name: Custo environment variables
        env:
          CUSTOM_MESSAGE: "Hello from Github Actions"
        run: echo "$CUSTOM_MESSAGE"

      - name: Conditional Execution
        if: github.event_name == 'push'
        run: echo "This was triggered by a push event"
