name: Basic Checkout Lab

# Trigger workflow on push to the main branh
on:
  push:
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    
    # Add a custom environment variable to the job
    env:
      CUSTOM_MESSAGE: "Hello from Github Actions"

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # List repository contents
      - name: List files
        run: ls -la

      # Display system information
      - name: Show system info
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Operating System: $(uname -a)"
          echo "Current Directory: $(pwd)"
          echo "Current Date and Time: $(date)"
          echo "Available Disk Space: $(df -h)"
          echo "Memory Usage: $(free -m)"

      # Check software versions
      - name: Check versions
        run: |
          echo "Node version: $(node --version)"
          echo "Python version: $(python --version)"
          echo "Git version: $(git --version)"

      - name: Display custom message
        # Without pipe (|), you would get error: 
        # "Nested mappings are not allowed in compact mappings at line 44, column 14: run: echo 'Custom message: $CUSTOM_MESSAGE' ^"
        # Otherwise you have write like this: echo "$CUSTOM_MESSAGE"
        run: echo "Custom message $CUSTOM_MESSAGE"

      # Conditional Execution
      - name: Conditional step
        if: github.event_name == 'push'
        run: echo "This was triggered by a push event"
